Module2 task1
htmlacademy-vue/1325833-pizza-1 pull request #2
Opened 2021-07-11 13:47 UTC by blurryfacebeat

2021-07-11 14:56 UTC, Djaler requested changes

2021-07-11 14:56 UTC, Djaler commented on src/frontend/src/common/components/AppDrag.vue
> +      type: Object
required должно быть, я думаю

2021-07-11 14:56 UTC, Djaler commented on src/frontend/src/common/components/ButtonWidget.vue
> +      default: () => {
default в виде функции имеет смысл только для объектов и массивов

2021-07-11 14:56 UTC, Djaler commented on src/frontend/src/common/components/ButtonWidget.vue
> +      this.$emit('clickHandler');
не критично, конечно, но так именовать события не принято. В данном случае просто `click` подошло бы

2021-07-11 14:56 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderDoughSelector/BuilderDoughSelector.vue
> +        <BuilderDoughSelectorItem
хорошо бы в таких местах работать с компонентами через v-model.
ну и тут явно напрашивается вынесение одного общего компонента для радио-баттона, чтобы не повторять одно и то же.
https://gist.github.com/Jonarod/8553d88b1b0d1e1898ff1b5c951b00cc вот тут неплохой пример кастомно компонента для радио-баттона

2021-07-11 14:56 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderResult/BuilderResultView.vue
> +    setIngredientCounterClass(count) {
в ТЗ не совсем очевидно написано, но мне почему-то кажется, что в случае, когда добавлено 2 или 3 одинаковых ингредиента, должно быть, соответственно, 2 или 3 div'а. Первый без дополнительного класса, второй с pizza__filling и т.д. 
Это выглядит логичнее с точки зрения отображения. Но можешь уточнить этот момент у авторов, если что

2021-07-11 14:56 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      this.calculatePizzaCost();
вот тут тебе приходится явно вызывать метод, потому что не срабатывает автоматически вотчер. а вотчер не срабатывает, потому что в компоненте BuilderIngredientsSelector в методе changeIngredients ты делаешь `this.ingredients[value.name] = value`. во 2 вью так делать нельзя, теряется реактивноть при добавлении новых свойств в объект. аналогично, нельзя делать `delete this.ingredients[value.name]`. нужно использовать Vue.set и Vue.delete в таких ситуациях

2021-07-11 14:56 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    calculatePizzaCost() {
ну и мне видится, что это должно быть computed свойством, а не методом+вотчером

2021-07-11 15:16 UTC, blurryfacebeat commented on src/frontend/src/common/components/ButtonWidget.vue
> +      this.$emit('clickHandler');
А как принято?

2021-07-11 15:30 UTC, Djaler commented on src/frontend/src/common/components/ButtonWidget.vue
> +      this.$emit('clickHandler');
Так, чтобы при добавлении `on` получалось осмысленное словосочетание. On click, on save, on ingredients change

2021-07-11 15:41 UTC, blurryfacebeat commented on src/frontend/src/views/Index.vue
> +      this.calculatePizzaCost();
Спасибо! Это решило кучу проблем. А я все искал источник проблемы с реактивным отображением. Приходилось какие-то костыли с :key делать.

2021-07-11 15:51 UTC, blurryfacebeat commented on src/frontend/src/views/Index.vue
> +    calculatePizzaCost() {
Тогда, если не использовать вотчер на объект, мне придется отправлять цену отдельным параметром. А мне хочется держать всю инфу о пицце в одном объекте и отправлять одним пропсом.
Или есть еще какой-то способ мне с помощью комьютеда в объект с инфой о пицце цену вставить?

2021-07-11 15:55 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    calculatePizzaCost() {
а почему бы вообще информацию о цене не высчитывать в самом BuilderResult?

2021-07-11 15:57 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    calculatePizzaCost() {
ну и в любом случае - можно в data держать данные о конфигурации пиццы, отдельным компьютедом считать цену, а ещё одним - собирать в один объект конфигурацию пиццы и цену для передачи в компонент результата

2021-07-12 16:56 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderResult/BuilderResultView/BuilderResultView.vue
> +          this.$set(this.pizzaResult.ingredients[key]);
computed не должен никаким образом менять состояние. только вычислять  новое

2021-07-13 13:56 UTC, merged